# SPDX-FileCopyrightText: 2020 Liz Clark for Adafruit Industries
#
# SPDX-License-Identifier: MIT

# This file is where you keep private settings, passwords, and tokens!
# If you put them in the code you risk committing that info or sharing it

CIRCUITPY_WIFI_SSID="your-wifi-ssid"
CIRCUITPY_WIFI_PASSWORD="your-wifi-password"
timezone="America/New_York"  # http://worldtimeapi.org/timezones
twitter_api_key="insert your twitter api key here"
twitter_secret_key="insert your twitter secret key here"
bearer_token="insert your bearer token here"
